-- =======================================================
-- DigiFin Quest — Initial Seed Data for MySQL
-- Password Admin default: admin123
-- Password Mahasiswa default: student123
-- =======================================================

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `simulation_results`;
TRUNCATE TABLE `sim_events`;
TRUNCATE TABLE `scenario_results`;
TRUNCATE TABLE `scenarios`;
TRUNCATE TABLE `claimed_challenges`;
TRUNCATE TABLE `user_badges`;
TRUNCATE TABLE `quiz_scores`;
TRUNCATE TABLE `completed_lessons`;
TRUNCATE TABLE `quizzes`;
TRUNCATE TABLE `modules`;
TRUNCATE TABLE `users`;

SET FOREIGN_KEY_CHECKS = 1;

-- 1. SEED ADMIN USER
INSERT INTO `users` (`id`, `email`, `name`, `password`, `role`, `points`, `streak`, `todayLessons`, `joinedAt`, `updatedAt`) VALUES
('9ec67a4e-d875-417f-b3e5-87ee36b980b0', 'admin@digifinquest.ac.id', 'Admin DigiFin', '$2b$10$qBUrFnHFuHYgFZMriRo6nuk9T6f12Vdzr0qS/MF3H4TKcJyAbi.2i', 'ADMIN', 0, 1, 0, NOW(), NOW());

-- 2. SEED SAMPLE STUDENTS
INSERT INTO `users` (`id`, `email`, `name`, `password`, `role`, `points`, `streak`, `todayLessons`, `joinedAt`, `updatedAt`) VALUES
('bdd360c9-413b-4b4f-84b5-b6eb880fe6c3', 'ayu@student.ac.id', 'Ayu P.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 1240, 1, 0, NOW(), NOW()),
('6985f513-1c2d-4846-83ca-0a6bb98f9d4e', 'budi@student.ac.id', 'Budi S.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 980, 1, 0, NOW(), NOW()),
('0be5ec60-6b08-4105-bf7b-dabb19a8bbfc', 'citra@student.ac.id', 'Citra W.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 760, 1, 0, NOW(), NOW()),
('2ae322c2-ef10-405b-b2a8-b2028e101569', 'dewi@student.ac.id', 'Dewi R.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 540, 1, 0, NOW(), NOW()),
('381d1aea-ea86-44d3-8a21-a181a84e5bab', 'eko@student.ac.id', 'Eko H.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 410, 1, 0, NOW(), NOW()),
('34f6614b-4614-4d54-9c22-a092a1744e95', 'fitri@student.ac.id', 'Fitri N.', '$2b$10$qknu8Fc9WHhWpPFDyu/54uDFDwIEZ4kR42mt2rrm.fXwaQJ5hIOTa', 'STUDENT', 300, 1, 0, NOW(), NOW());

-- 3. SEED MODULES & QUIZZES
INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'm1', 'Fintech Basics', '["Definisi Fintech","Jenis Fintech","Ekosistem","Manfaat & Risiko"]', 1, '{"intro":"Fintech (financial technology) adalah pemanfaatan teknologi untuk menghadirkan layanan keuangan. Modul ini membangun fondasi: apa itu fintech, jenis-jenisnya, siapa pemainnya, serta manfaat dan risikonya.","sections":[{"h":"Definisi Fintech","b":"Fintech adalah layanan keuangan yang dihantarkan melalui teknologi — mencakup pembayaran, pinjaman, investasi, hingga asuransi. Batasnya bukan ''perusahaan teknologi'' melainkan ''layanan keuangan berbasis teknologi''."},{"h":"Jenis Fintech","b":"Kategori utama: pembayaran (e-wallet, transfer), lending (termasuk peer-to-peer), wealthtech (investasi digital, robo-advisor), insurtech (asuransi), dan regtech (kepatuhan). Memahami kategori membantu menilai risiko tiap layanan."},{"h":"Ekosistem","b":"Ekosistem fintech menghubungkan penyedia, bank, regulator (di Indonesia: OJK dan Bank Indonesia sesuai ranahnya), dan konsumen. Interoperabilitas (mis. QRIS) membuat sistem berbeda dapat bekerja sama."},{"h":"Manfaat & Risiko","b":"Manfaat utama: inklusi keuangan, biaya lebih rendah, kemudahan akses. Risiko: penipuan, keterlilitan utang, dan penyalahgunaan data. Keberadaan izin adalah salah satu sinyal paling jelas pembeda penyedia aman dari yang berbahaya."}],"example":{"title":"Contoh penerapan — mengenali jenis fintech","body":"Aplikasi A menyimpan saldo dan memindai QR untuk bayar di warung (pembayaran/e-wallet). Aplikasi B mempertemukan Anda dengan investor yang mendanai pinjaman Anda (lending/P2P). Aplikasi C menyusun portofolio reksa dana otomatis sesuai profil risiko (wealthtech/robo-advisor). Mengenali kategori membantu Anda menilai risiko sebelum memakai."},"takeaways":["Fintech = layanan keuangan yang dihantarkan melalui teknologi.","Kategori utama: payment, lending, wealthtech, insurtech, regtech.","Regulator di Indonesia: OJK dan Bank Indonesia sesuai ranahnya.","Cek status izin sebelum memakai layanan apa pun."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('84b04720-39d3-499f-b5e9-bc0d46ebc124', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Fintech paling tepat didefinisikan sebagai:', '["Perusahaan media sosial","Layanan keuangan yang dihantarkan melalui teknologi","Toko gawai elektronik","Jenis mata uang"]', 1, 'Fintech adalah layanan keuangan berbasis teknologi, bukan sekadar perusahaan teknologi.', 'mudah', 0),
('22b5b39c-6e3c-443f-834b-2d2839775825', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Manakah yang termasuk kategori fintech pembayaran?', '["E-wallet","Konstruksi gedung","Restoran","Agen perjalanan"]', 0, 'E-wallet adalah contoh fintech kategori pembayaran.', 'mudah', 1),
('fefb8381-e7ba-430a-910b-6f5b22b429d9', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Robo-advisor termasuk kategori fintech:', '["Insurtech","Wealthtech","Regtech","Pembayaran"]', 1, 'Robo-advisor mengotomatiskan investasi, termasuk wealthtech.', 'sedang', 2),
('e6afbe06-54c8-41f9-8097-64daf06dd2c2', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Di Indonesia, pengawasan sistem pembayaran terutama menjadi ranah:', '["Bursa Efek","Bank Indonesia","Kementerian Perdagangan","Lembaga internasional"]', 1, 'Aspek sistem pembayaran terutama menjadi ranah Bank Indonesia.', 'sedang', 3),
('bafa6180-776f-4ca7-a5f8-8d8e1e79b8aa', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Manfaat utama fintech bagi masyarakat luas adalah:', '["Menambah birokrasi","Inklusi keuangan bagi yang kurang terlayani bank","Memperlambat transaksi","Menaikkan biaya"]', 1, 'Fintech dapat menjangkau populasi yang kurang terlayani perbankan tradisional.', 'mudah', 4),
('8c9853e4-b854-4430-91f7-32d6515f19c1', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'QRIS memungkinkan:', '["Satu kode QR dibayar lintas aplikasi/bank berbeda","Bunga dijamin","Pinjaman tanpa bunga","Transfer anonim"]', 0, 'QRIS menstandarkan QR sehingga satu kode berlaku lintas penyedia.', 'sedang', 5),
('15f044fc-d550-4210-9a1c-d2a679de4112', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Regtech adalah teknologi yang membantu:', '["Menambang kripto","Perusahaan memenuhi kepatuhan dan regulasi","Mendaftarkan domain","Mempercepat game"]', 1, 'Regtech mengotomatiskan kepatuhan, pelaporan, dan pemantauan risiko.', 'sulit', 6),
('7dc28f0f-6d93-44ed-b8c4-d758a76cc088', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Sinyal paling jelas pembeda penyedia fintech aman dari berbahaya adalah:', '["Warna aplikasi","Status izin/legalitas","Jumlah iklan","Ukuran file aplikasi"]', 1, 'Status izin adalah sinyal kunci legalitas dan keamanan penyedia.', 'sedang', 7),
('bf5dcf5a-1da5-4c1f-98c2-2cd0998c3394', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Insurtech menerapkan teknologi pada bidang:', '["Asuransi","Pertambangan","Konstruksi","Pertanian saja"]', 0, 'Insurtech membaharui cara asuransi dirancang dan dihantarkan.', 'mudah', 8),
('9a27309a-5438-403d-a0d4-513fe68dfbc7', 'f08ade4d-bbea-42bb-bcb9-84847f0656f3', 'Interoperabilitas dalam ekosistem fintech berarti:', '["Hanya satu penyedia boleh beroperasi","Sistem/penyedia berbeda dapat bekerja sama","Wajib memakai uang tunai","Tiap toko butuh kode berbeda"]', 1, 'Interoperabilitas memungkinkan penyedia berbeda saling bertransaksi dengan mulus.', 'sulit', 9);

INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('fe1f03e9-3f25-4352-926d-8222d3238972', 'm2', 'Digital Payment & E-Wallet', '["E-wallet","QRIS","Mobile Banking","Keamanan Transaksi"]', 2, '{"intro":"Pembayaran digital memindahkan nilai tanpa uang tunai. Kemudahannya tinggi, tetapi taruhan keamanannya juga tinggi.","sections":[{"h":"E-wallet","b":"E-wallet menyimpan saldo digital untuk pembayaran dan transfer. Saldo tersimpan (''float'') hanya seaman penyedia yang menyimpannya, sehingga memakai penyedia berizin penting."},{"h":"QRIS","b":"QRIS (Quick Response Code Indonesian Standard) memungkinkan satu kode QR dibayar oleh banyak aplikasi dan bank berbeda."},{"h":"Mobile Banking","b":"Mobile banking membawa kendali penuh atas rekening ke ponsel. Kemudahan ini memusatkan risiko pada perangkat."},{"h":"Keamanan Transaksi","b":"Kebiasaan inti: jangan pernah membagikan OTP — bank tidak pernah memintanya; aktifkan notifikasi transaksi; hindari transaksi lewat Wi-Fi publik tak tepercaya."}],"example":{"title":"Contoh penerapan — mengenali penipuan pembayaran","body":"Pesan berbunyi: ''Akun terkunci. Kirim OTP dan transfer Rp50.000 untuk verifikasi.'' Dua tanda bahaya: lembaga sah tidak pernah meminta OTP, dan tidak pernah meminta Anda mengirim uang untuk ''memverifikasi'' diri."},"takeaways":["QRIS menstandarkan QR sehingga satu kode berlaku lintas penyedia.","Jangan pernah membagikan OTP; bank tidak pernah memintanya.","Verifikasi keaslian aplikasi; gunakan 2FA/biometrik.","Aktifkan notifikasi untuk mendeteksi transaksi tak sah."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('f2e607ff-7e3f-4560-94f7-5f51cf84bd38', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'QRIS di Indonesia terutama menstandarkan:', '["Suku bunga","Pembayaran kode QR lintas penyedia","Perdagangan saham","Persetujuan pinjaman"]', 1, 'QRIS menyatukan pembayaran QR lintas penyedia.', 'mudah', 0),
('f9cca4a3-1d4d-41dd-9838-5ae66326257d', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'E-wallet adalah:', '["Dompet kulit fisik","Akun digital penyimpan dana untuk transaksi elektronik","Sejenis pinjaman","Skor kredit"]', 1, 'E-wallet menyimpan saldo digital untuk pembayaran dan transfer.', 'mudah', 1),
('267e8125-b7ec-4320-b887-6b17045fdbfc', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Praktik yang PALING meningkatkan keamanan mobile banking:', '["Membagikan OTP ke petugas","PIN unik kuat + biometrik/2FA","Menyimpan sandi di catatan publik","Transaksi via Wi-Fi publik"]', 1, 'Autentikasi kuat dan 2FA melindungi akses.', 'sedang', 2),
('f3a990f6-e02e-489d-8a6f-a93be46d46f5', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'OTP seharusnya:', '["Dibagikan bila diminta","Dirahasiakan, tidak diungkap ke pihak ketiga","Diumumkan publik","Dipakai ulang tiap login"]', 1, 'OTP mengautentikasi Anda; mengungkapkannya berarti menyerahkan akses.', 'mudah', 3),
('bdc0e9e8-a125-4553-bc38-58eb5182b237', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Saldo ''float'' e-wallet berisiko jika:', '["Anda aktifkan 2FA","Penyedia tidak berizin dan bangkrut","Anda cek saldo sering","Anda pakai QRIS"]', 1, 'Penyedia tak diatur membawa risiko atas dana tersimpan.', 'sulit', 4),
('1c1713e3-1447-476d-a860-14416adc36ba', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Pembayaran nirsentuh/NFC bekerja dengan:', '["Mengirim tunai lewat pos","Komunikasi nirkabel jarak dekat perangkat-terminal","Menelepon bank","Sidik jari di ATM"]', 1, 'NFC memungkinkan bayar-tempel pada jarak beberapa sentimeter.', 'sedang', 5),
('33baf158-2177-4824-b864-5eaaf90e1ab6', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Tanda bahaya saat pembayaran digital:', '["Pedagang menampilkan QRIS resmi","Diminta transfer ke rekening pribadi ''untuk verifikasi''","Struk dikirim ke aplikasi","Notifikasi transaksi"]', 1, 'Verifikasi sah tidak pernah meminta transfer ke rekening pribadi.', 'sedang', 6),
('176c530e-2d10-4082-8e9a-67fca511f27f', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Notifikasi transaksi berharga karena:', '["Menambah biaya","Memungkinkan deteksi cepat aktivitas tak sah","Memperlambat bayar","Mengganti sandi"]', 1, 'Notifikasi real-time memunculkan penipuan cepat.', 'mudah', 7),
('5fc2f3aa-9b91-40e4-b758-e0365d6b01d6', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Sebelum mengunduh aplikasi perbankan, verifikasi:', '["Skema warna","Penerbit & sumber resmi","Jumlah iklan","Hanya ukuran file"]', 1, 'Verifikasi penerbit mencegah aplikasi palsu/berbahaya.', 'sedang', 8),
('6ad92491-3d26-427d-820a-ab2f3fa02ae6', 'fe1f03e9-3f25-4352-926d-8222d3238972', 'Wi-Fi publik berisiko untuk perbankan karena:', '["Selalu lebih cepat","Lalu lintas bisa disadap di jaringan tak aman","Memblokir semua aplikasi","Mengenkripsi otomatis"]', 1, 'Jaringan tak aman memungkinkan penyadapan.', 'sulit', 9);

INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('00fae681-cb60-40a7-9428-1e6b53e60bc9', 'm3', 'Budgeting & Personal Finance', '["Penganggaran","Menabung","Dana Darurat","Perencanaan"]', 3, '{"intro":"Mengelola keuangan pribadi adalah fondasi sebelum memakai produk fintech apa pun.","sections":[{"h":"Penganggaran","b":"Anggaran adalah rencana mengalokasikan penghasilan ke kebutuhan, keinginan, dan tabungan. Kerangka awal umum: 50/30/20."},{"h":"Menabung","b":"Kebiasaan ampuh adalah ''membayar diri sendiri lebih dahulu'': otomatiskan transfer ke tabungan begitu penghasilan diterima."},{"h":"Dana Darurat","b":"Dana darurat adalah tabungan likuid yang menutup sekitar 3–6 bulan pengeluaran pokok."},{"h":"Perencanaan","b":"Tujuan efektif bersifat SMART: Spesifik, Terukur, Dapat dicapai, Relevan, Berbatas waktu."}],"example":{"title":"Contoh penerapan — menerapkan 50/30/20","body":"Mahasiswa berpenghasilan Rp3.000.000/bulan. Dengan 50/30/20: ~Rp1.500.000 kebutuhan, ~Rp900.000 keinginan, ~Rp600.000 tabungan/utang."},"takeaways":["Anggaran mengalokasikan penghasilan dengan sengaja.","Otomatiskan tabungan (''bayar diri sendiri dulu'').","Bangun dana darurat 3–6 bulan sebelum berinvestasi.","Pantau kekayaan bersih untuk melihat kemajuan nyata."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('c964efb8-19d3-492f-849a-2ad99fb22bd1', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Tujuan utama anggaran pribadi:', '["Menghapus semua pengeluaran","Merencanakan alokasi penghasilan","Menambah utang","Menghindari bank"]', 1, 'Anggaran mengalokasikan penghasilan dengan sengaja.', 'mudah', 0),
('2b29acfa-8aa2-4c25-b97f-9581fc22a869', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Aturan 50/30/20 mengalokasikan 20% untuk:', '["Keinginan","Kebutuhan","Tabungan & pelunasan utang","Hiburan"]', 2, '20% untuk tabungan/pelunasan utang.', 'mudah', 1),
('6903e1a0-567a-407c-9e5a-86cddb6f7af2', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Dana darurat paling tepat adalah:', '["Uang di saham","Tabungan likuid 3–6 bulan pengeluaran pokok","Limit kartu kredit","Tabungan pensiun"]', 1, 'Dana darurat harus likuid dan menutup biaya pokok.', 'sedang', 2),
('e2590bc4-0f10-447a-a010-8beb05dce868', '00fae681-cb60-40a7-9428-1e6b53e60bc9', '''Kebutuhan'', bukan ''keinginan'':', '["Langganan streaming","Tempat tinggal","Gawai baru","Makan di luar"]', 1, 'Tempat tinggal bersifat pokok.', 'mudah', 3),
('1967fe2c-71c8-42ae-bb30-f9c599ae7c04', '00fae681-cb60-40a7-9428-1e6b53e60bc9', '''Membayar diri sendiri dulu'' berarti:', '["Belanja diri sebelum tagihan","Menabung otomatis sebelum belanja diskresioner","Ambil uang muka gaji","Beli barang mewah dulu"]', 1, 'Memprioritaskan menabung dengan otomatisasi.', 'sedang', 4),
('02b964b9-2a18-4ee6-a225-c152aa003e4b', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Bunga majemuk berarti bunga atas:', '["Hanya pokok","Pokok + bunga terakumulasi sebelumnya","Inflasi saja","Biaya bank"]', 1, 'Bunga atas bunga mempercepat pertumbuhan.', 'sedang', 5),
('2979eb96-3fce-4c2f-963d-546041b28770', '00fae681-cb60-40a7-9428-1e6b53e60bc9', '''T'' dalam tujuan SMART berarti:', '["Berisiko","Berbatas waktu (Time-bound)","Bebas pajak","Tak terbatas"]', 1, 'T = Time-bound, ada batas waktu.', 'mudah', 6),
('8a0b194c-d91e-4c73-9e78-a1889fbbe8d7', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Inflasi gaya hidup adalah:', '["Naiknya harga toko","Naiknya pengeluaran saat penghasilan naik, menggerus tabungan","Perubahan bunga","Pelemahan mata uang"]', 1, 'Pengeluaran tumbuh mengikuti penghasilan.', 'sulit', 7),
('39a0826d-c3a7-4a9b-ac16-da0c4115d70f', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Alat terbaik melacak pengeluaran harian otomatis:', '["Buku kertas saja","Aplikasi pencatat terhubung rekening","Kalkulator","Obligasi"]', 1, 'Aplikasi terhubung mencatat transaksi otomatis.', 'mudah', 8),
('62ae7649-98c8-4cb7-a77f-b30ec56d6d9d', '00fae681-cb60-40a7-9428-1e6b53e60bc9', 'Kekayaan bersih dihitung sebagai:', '["Penghasilan - pengeluaran","Aset - liabilitas","Tabungan + gaji","Total pengeluaran tahunan"]', 1, 'Kekayaan bersih = yang dimiliki - yang diutangkan.', 'sedang', 9);

INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'm4', 'Fintech Lending / Pinjaman Online', '["P2P Lending","Pinjol Legal vs Ilegal","Bunga & Biaya","Risiko Utang"]', 4, '{"intro":"Fintech lending (pinjaman online) memperluas akses kredit, tetapi membawa risiko nyata.","sections":[{"h":"P2P Lending","b":"P2P lending mempertemukan peminjam dan pemberi pinjaman tanpa bank perantara."},{"h":"Pinjol Legal vs Ilegal","b":"Pinjol legal terdaftar di OJK; pinjol ilegal sering menawarkan ''cair tanpa syarat'' dan menyalahgunakan data."},{"h":"Bunga & Biaya","b":"Pahami total biaya pinjaman termasuk bunga, biaya admin, dan denda keterlambatan."},{"h":"Risiko Utang","b":"Pola ''gali lubang tutup lubang'' memperbesar total utang secara eksponensial."}],"example":{"title":"Contoh penerapan — menghitung total biaya pinjaman","body":"Pinjaman Rp1.000.000 dengan bunga 0,8%/hari selama 30 hari = bunga Rp240.000 (24%). Total bayar Rp1.240.000."},"takeaways":["Selalu cek status legalitas pinjol di OJK.","Hitung total biaya pinjaman sebelum mengambil.","Jangan gunakan pinjaman baru untuk menutup pinjaman lama.","Pinjam hanya untuk kebutuhan mendesak, bukan keinginan."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('2fad27c6-4642-4d55-80ea-d019436f84de', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'P2P lending berarti:', '["Pinjaman dari pemerintah","Peminjam & pemberi pinjaman terhubung langsung tanpa bank","Deposito bank","Kartu kredit"]', 1, 'P2P mempertemukan peminjam-pemberi pinjaman langsung.', 'mudah', 0),
('f4e01674-4bdf-44d2-b94a-36cc850338c6', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Pinjol ilegal biasanya:', '["Terdaftar di OJK","Menawarkan ''cair tanpa syarat'' & minta akses kontak","Bunga rendah","Diawasi pemerintah"]', 1, 'Pinjol ilegal menjebak dengan kemudahan palsu.', 'mudah', 1),
('90a82c54-59a3-4c06-8ebe-bb8ced0d04f4', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Bunga 0,8%/hari selama 30 hari setara:', '["0,8% total","24% total","8% total","80% total"]', 1, '0,8% × 30 hari = 24%.', 'sedang', 2),
('fedd30b6-2a47-42b2-a79a-4b5c7e02c201', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', '''Gali lubang tutup lubang'' berarti:', '["Menabung rutin","Meminjam untuk membayar pinjaman lain","Investasi diversifikasi","Membayar tepat waktu"]', 1, 'Pola ini memperbesar total utang.', 'mudah', 3),
('0ae67b23-6657-42aa-b637-280eacface18', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Sebelum meminjam, yang HARUS dihitung:', '["Warna aplikasi","Total biaya termasuk bunga & biaya admin","Jumlah unduhan","Rating aplikasi saja"]', 1, 'Total biaya menunjukkan beban sebenarnya.', 'sedang', 4),
('b75c9d19-8466-4fa5-a779-4e421cf154d3', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Tanda pinjol legal:', '["Iklan di media sosial","Terdaftar/berizin di OJK","Cair 5 menit","Tanpa syarat"]', 1, 'Status OJK adalah penanda utama legalitas.', 'mudah', 5),
('50709dea-3458-4f54-ac48-16ee2ed11a2c', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Risiko terbesar pinjaman konsumtif:', '["Bunga rendah","Keterlilitan utang berlebihan","Meningkatkan tabungan","Menambah aset"]', 1, 'Pinjaman konsumtif tanpa perencanaan menjerat utang.', 'sedang', 6),
('271f7870-9094-4627-8789-e4d9c9568da4', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Denda keterlambatan pinjol berfungsi:', '["Mengurangi utang","Menambah beban total pinjaman","Menghapus bunga","Memberi diskon"]', 1, 'Denda memperbesar total yang harus dibayar.', 'sedang', 7),
('76e7945f-ac1f-4f37-9454-53957c6f651a', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Pinjaman sebaiknya diambil untuk:', '["Beli gawai impian","Kebutuhan mendesak yang terencana","Ikut tren","Investasi bodong"]', 1, 'Pinjaman untuk kebutuhan mendesak dengan perhitungan matang.', 'sulit', 8),
('7f198714-c330-439c-8383-5f5703b0ba34', '8954c4b9-b2cb-4a2b-9c62-03bae04bda87', 'Jika tidak mampu membayar pinjol legal:', '["Diam saja","Hubungi penyedia untuk negosiasi restrukturisasi","Pinjam lagi dari pinjol lain","Blokir nomor mereka"]', 1, 'Komunikasi dan negosiasi lebih baik daripada menghindari.', 'sulit', 9);

INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'm5', 'Digital Financial Security', '["Phishing","Social Engineering","Autentikasi 2FA","Perlindungan Data"]', 5, '{"intro":"Keamanan keuangan digital melindungi aset dan identitas Anda dari ancaman siber.","sections":[{"h":"Phishing","b":"Phishing menipu pengguna agar mengungkapkan kredensial melalui pesan/situs palsu."},{"h":"Social Engineering","b":"Serangan yang memanipulasi psikologi untuk mengakses informasi."},{"h":"Autentikasi 2FA","b":"2FA meminta bukti identitas kedua selain sandi, melindungi meski sandi bocor."},{"h":"Perlindungan Data","b":"Minimalisasi data: bagikan hanya yang perlu. Hindari transaksi di Wi-Fi publik."}],"example":{"title":"Contoh penerapan — mengenali phishing","body":"Email dari ''bank'' meminta klik tautan dan masukkan PIN. Bank asli tidak pernah meminta kredensial lewat email."},"takeaways":["Jangan klik tautan mencurigakan; verifikasi lewat saluran resmi.","Aktifkan 2FA pada semua akun keuangan.","Terapkan minimalisasi data: bagikan hanya yang perlu.","Hindari transaksi di Wi-Fi publik; perbarui perangkat lunak."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('79f59c37-2fac-4db6-968f-438e01143898', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Phishing adalah upaya untuk:', '["Menaikkan skor kredit","Mengelabui agar mengungkapkan kredensial/data pribadi","Menaikkan bunga","Memasang antivirus"]', 1, 'Phishing menipu pengguna agar menyerahkan informasi sensitif.', 'mudah', 0),
('0516b3d4-aa4c-440d-be85-706fce588c0f', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Tanda bahaya phishing klasik:', '["Pesan teman soal makan siang","Desakan meminta sandi/OTP lewat tautan","Mutasi bulanan di aplikasi","Pemberitahuan libur bank"]', 1, 'Desakan + permintaan kredensial lewat tautan adalah ciri phishing.', 'mudah', 1),
('e9809ab8-e136-4c4c-96ab-5bfa4352c8a1', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', '2FA melindungi dengan:', '["Meminta bukti identitas kedua selain sandi","Menghapus kebutuhan sandi","Membagikan data luas","Menonaktifkan notifikasi"]', 0, '2FA menambah faktor kedua.', 'sedang', 2),
('b38ccd22-1e8b-4eac-8008-bac6bd666409', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Jika ''bank'' menelepon meminta PIN & OTP lengkap, Anda:', '["Memberikannya segera","Menolak & hubungi bank lewat saluran resmi","Mengumumkan daring","Mengirim lewat email"]', 1, 'Bank tidak pernah meminta PIN/OTP lengkap.', 'mudah', 3),
('0d296120-95cd-4a2d-9d89-687b90f48b6a', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Kata sandi kuat adalah:', '["Tanggal lahir","Panjang, unik, tak dipakai ulang","''123456''","Nama hewan peliharaan"]', 1, 'Panjang, unik, tak dipakai ulang mengalahkan serangan umum.', 'mudah', 4),
('fbaef044-d3a4-4a10-b94b-52e039c9b67f', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', '''Smishing'' adalah phishing lewat:', '["Email","SMS","Telepon","Faks"]', 1, 'Smishing dihantarkan melalui SMS.', 'sedang', 5),
('3ab13d10-f05e-45d1-8f70-472d3c6d4dd0', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Skema Ponzi membayar dengan:', '["Keuntungan nyata","Uang investor baru untuk investor lama","Hibah pemerintah","Bunga bank"]', 1, 'Ponzi membayar investor lama dari setoran baru sampai runtuh.', 'sulit', 6),
('fbfe4e6e-e64a-43b0-8b1d-13fe61d52117', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Minimalisasi data berarti:', '["Mengumpulkan sebanyak mungkin","Berbagi/mengumpulkan hanya yang perlu","Hapus semua akun","Tidak mengenkripsi"]', 1, 'Minimalisasi membatasi eksposur data.', 'sulit', 7),
('286b9c44-ecd2-403e-95fc-eaf00fb070fd', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Wi-Fi publik berisiko karena:', '["Selalu lebih cepat","Lalu lintas bisa disadap di jaringan tak aman","Memblokir aplikasi","Mengenkripsi otomatis"]', 1, 'Jaringan tak aman memungkinkan penyadapan.', 'sedang', 8),
('3b784123-f879-47a5-ad1e-7662379463af', '1c850b60-7b65-4c9a-8e53-0eb343908aa7', 'Tawaran ''imbal hasil tinggi dijamin tanpa risiko'' adalah:', '["Peluang bagus","Tanda kuat penipuan","Selalu sah","Dijamin pemerintah"]', 1, 'Imbal hasil tinggi dijamin tanpa risiko adalah tanda bahaya.', 'mudah', 9);

INSERT INTO `modules` (`id`, `slug`, `title`, `topics`, `order_num`, `lesson`) VALUES
('0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'm6', 'Consumer Protection', '["Hak Konsumen","Penyelesaian Sengketa","Transparansi","Pengaduan"]', 6, '{"intro":"Perlindungan konsumen memastikan pengguna layanan keuangan digital diperlakukan adil.","sections":[{"h":"Hak Konsumen","b":"Konsumen berhak atas informasi yang jelas dan jujur, perlakuan adil, kerahasiaan data, serta akses terhadap penyelesaian keluhan."},{"h":"Transparansi","b":"Sebelum menyetujui produk, konsumen berhak tahu biaya total, bunga, denda, dan ketentuan."},{"h":"Pengaduan","b":"Jika dirugikan, konsumen dapat mengadu ke penyedia, lalu ke kanal pengaduan resmi (OJK)."},{"h":"Penyelesaian Sengketa","b":"Sengketa dapat diselesaikan melalui mediasi atau lembaga alternatif penyelesaian sengketa."}],"example":{"title":"Contoh penerapan — menggunakan hak konsumen","body":"Seorang pengguna dikenai biaya yang tidak dijelaskan di awal. Langkahnya: kumpulkan bukti, ajukan keluhan tertulis ke penyedia, bila tak selesai teruskan ke OJK."},"takeaways":["Konsumen berhak atas informasi jujur, perlakuan adil, dan kerahasiaan data.","Ketahui total biaya & ketentuan sebelum menyetujui produk.","Simpan bukti; adukan ke penyedia lalu kanal resmi (OJK).","Sengketa dapat diselesaikan via mediasi sebelum jalur hukum."]}');

INSERT INTO `quizzes` (`id`, `moduleId`, `question`, `options`, `answer`, `explanation`, `difficulty`, `order_num`) VALUES
('ffb31192-8ed2-4c32-9418-693bcf26bb7b', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Hak dasar konsumen layanan keuangan meliputi:', '["Tidak berhak apa pun","Informasi jujur, perlakuan adil, kerahasiaan data","Hanya hak komplain","Hanya potongan harga"]', 1, 'Konsumen berhak atas informasi jujur, perlakuan adil, dan kerahasiaan data.', 'mudah', 0),
('3e188c5c-92ae-4a11-ba7a-a0a27010db4a', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Sebelum menyetujui produk keuangan, konsumen berhak tahu:', '["Warna logo","Total biaya, bunga, denda, ketentuan","Jumlah karyawan","Lokasi kantor saja"]', 1, 'Transparansi biaya dan ketentuan adalah hak konsumen.', 'mudah', 1),
('9bc49755-2530-49e2-8f1c-814433970830', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Tanda bahaya terkait transparansi:', '["Biaya dijelaskan di awal","Biaya disembunyikan & tekanan untuk segera setuju","Ada ringkasan ketentuan","Ada nomor layanan resmi"]', 1, 'Menyembunyikan biaya dan menekan adalah tanda bahaya.', 'sedang', 2),
('27f696d4-23c9-4463-89ce-568c859d0058', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Langkah pertama bila dirugikan penyedia:', '["Diam saja","Mengadu ke penyedia dengan bukti, lalu kanal resmi","Menyebar di media sosial tanpa bukti","Berhenti memakai semua aplikasi"]', 1, 'Adukan ke penyedia dahulu, lalu kanal resmi, dengan bukti.', 'sedang', 3),
('96f312b0-f39e-4933-af05-8dcc7be5f7a9', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Yang penting disimpan sebagai bukti sengketa:', '["Tidak ada","Tangkapan layar, perjanjian, riwayat transaksi","Hanya nama aplikasi","Hanya rating"]', 1, 'Dokumentasi memperkuat posisi konsumen.', 'mudah', 4),
('98d4d583-463a-4001-9475-b9721e74be0e', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Di Indonesia, pengaduan layanan keuangan dapat diteruskan melalui:', '["Tidak ada lembaga","Mekanisme melalui OJK","Hanya kepolisian","Hanya media massa"]', 1, 'Tersedia mekanisme pengaduan melalui OJK.', 'sedang', 5),
('68a34e37-2b27-4c40-91ef-2b9a6911c9a5', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Penyelesaian sengketa sebaiknya diupayakan melalui:', '["Langsung jalur hukum","Mediasi/lembaga alternatif sebelum jalur hukum","Tidak diselesaikan","Balas dendam"]', 1, 'Mediasi/alternatif diupayakan sebelum jalur hukum.', 'sulit', 6),
('f5560a3a-55f1-46ff-8425-2efede671c2b', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Kerahasiaan data konsumen berarti penyedia harus:', '["Menjual data ke pihak lain","Melindungi dan tidak menyalahgunakan data","Mengumumkan data publik","Mengabaikan keamanan"]', 1, 'Penyedia wajib melindungi data konsumen.', 'sedang', 7),
('8afb0257-bc7b-4b71-9c41-6d126c0ca358', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Transparansi biaya adalah:', '["Kebaikan opsional penyedia","Hak konsumen","Hal yang tidak penting","Hanya untuk nasabah besar"]', 1, 'Transparansi adalah hak, bukan kemurahan penyedia.', 'mudah', 8),
('5d00bbff-4004-46c6-93a7-64ed568c7e14', '0654f247-bca9-4bc9-ac46-df1f1f918dd2', 'Perlindungan konsumen pada akhirnya bertujuan:', '["Menghambat industri","Memastikan perlakuan adil & menjaga kepercayaan","Menaikkan biaya","Mengurangi pilihan"]', 1, 'Tujuannya perlakuan adil dan menjaga kepercayaan sistem.', 'sedang', 9);

-- 4. SEED SCENARIOS
INSERT INTO `scenarios` (`id`, `slug`, `theme`, `situation`, `choices`, `order_num`) VALUES
('ab24c1fc-cb81-4f05-8e5d-ff07947b626d', 's1', 'Pinjaman Online', 'Anda butuh Rp2.000.000 mendesak. Sebuah iklan menawarkan ''cair 5 menit, tanpa syarat, cukup kirim KTP dan izinkan akses kontak''. Apa yang Anda lakukan?', '[{"t":"Langsung daftar, uang lebih penting sekarang","quality":0,"outcome":"Aplikasi ternyata pinjol ilegal. Bunga membengkak dan kontak Anda dihubungi untuk intimidasi saat telat bayar."},{"t":"Cek dulu status legalitasnya di OJK sebelum memutuskan","quality":2,"outcome":"Anda menemukan aplikasi itu tidak terdaftar. Anda menghindarinya dan mencari alternatif resmi."},{"t":"Tanya teman yang pernah pakai, ikut saja kalau dia aman","quality":1,"outcome":"Pengalaman satu orang bukan jaminan legalitas."}]', 1),
('e7d04824-7c74-4c24-b17a-8dfe2277bfc3', 's2', 'Investasi Bodong', 'Seorang kenalan mengajak investasi ''dijamin untung 15% per bulan, tanpa risiko'' asal Anda juga mengajak dua orang lain. Sikap Anda?', '[{"t":"Ikut, untungnya besar dan ada yang sudah dapat","quality":0,"outcome":"Ini ciri skema Ponzi/piramida. Skema runtuh dan dana Anda hilang."},{"t":"Tolak — ''untung tinggi dijamin tanpa risiko'' itu tidak ada","quality":2,"outcome":"Anda mengenali tanda bahaya klasik penipuan."},{"t":"Coba dengan uang kecil dulu untuk lihat hasilnya","quality":1,"outcome":"Skema sengaja membayar di awal untuk memancing setoran lebih besar."}]', 2),
('72b87554-bc00-4296-8b58-6cb34660c452', 's3', 'Phishing', 'Anda menerima SMS: ''Akun bank Anda diblokir. Klik tautan ini dan masukkan PIN serta OTP untuk mengaktifkan kembali.'' Tindakan Anda?', '[{"t":"Klik tautan dan masukkan data agar akun aktif lagi","quality":0,"outcome":"Tautan adalah situs palsu. Kredensial Anda dicuri."},{"t":"Abaikan SMS, buka aplikasi resmi/hubungi call center bank","quality":2,"outcome":"Anda memverifikasi lewat saluran resmi — ternyata tidak ada pemblokiran."},{"t":"Klik tautan untuk lihat dulu, tapi tidak isi data","quality":1,"outcome":"Mengklik tautan mencurigakan tetap berisiko."}]', 3),
('e58e59f5-ec60-4051-8c3b-5dafaf5e8536', 's4', 'QRIS Palsu', 'Di sebuah toko, kasir menempelkan stiker QR baru di atas QRIS resmi. Nama penerima yang muncul bukan nama toko. Apa yang Anda lakukan?', '[{"t":"Tetap bayar, mungkin itu rekening pemilik","quality":0,"outcome":"Dana masuk ke rekening penipu."},{"t":"Batalkan, konfirmasi ke kasir karena nama penerima tak sesuai","quality":2,"outcome":"Anda menyadari ketidaksesuaian dan menghindari penipuan."},{"t":"Bayar tunai saja tanpa menanyakan apa pun","quality":1,"outcome":"Anda terhindar, tetapi penipuan dibiarkan."}]', 4),
('a08aaf8f-c9ae-448e-9bc6-30b01a927102', 's5', 'Anggaran', 'Gaji pertama Anda Rp4.000.000 baru masuk. Ada diskon gawai impian Rp3.500.000 hari ini saja. Anda belum punya dana darurat. Keputusan Anda?', '[{"t":"Beli sekarang, mumpung diskon besar","quality":0,"outcome":"Anda kehabisan dana untuk kebutuhan."},{"t":"Tahan, sisihkan untuk kebutuhan & mulai dana darurat dulu","quality":2,"outcome":"Anda menerapkan prioritas keuangan yang sehat."},{"t":"Beli versi lebih murah dengan setengah uang","quality":1,"outcome":"Lebih baik, tetapi membeli keinginan sebelum dana darurat tetap berisiko."}]', 5),
('d245006f-e8b9-4237-984d-491e3066eba7', 's6', 'Perlindungan Konsumen', 'Anda dikenai biaya tersembunyi pada layanan keuangan digital yang tidak dijelaskan saat mendaftar. Langkah Anda?', '[{"t":"Diamkan saja, jumlahnya kecil","quality":0,"outcome":"Hak Anda terabaikan."},{"t":"Kumpulkan bukti, ajukan keluhan ke penyedia, lalu kanal resmi","quality":2,"outcome":"Anda menggunakan hak konsumen dengan benar."},{"t":"Marah-marah di media sosial tanpa bukti","quality":1,"outcome":"Keluhan tanpa dokumentasi lemah."}]', 6),
('ab076e4e-08d1-46c7-9d7a-cac9ddd76a1e', 's7', 'Keamanan Akun', 'Sebuah aplikasi baru meminta izin akses ke kontak, galeri, lokasi, dan mikrofon padahal fungsinya hanya pencatat keuangan. Sikap Anda?', '[{"t":"Setujui semua agar aplikasi cepat jalan","quality":0,"outcome":"Anda memberi akses berlebihan."},{"t":"Tolak izin yang tak relevan dengan fungsi aplikasi","quality":2,"outcome":"Anda menerapkan minimalisasi data."},{"t":"Setujui sebagian, tapi tidak yakin yang mana penting","quality":1,"outcome":"Lebih baik, tetapi risiko tetap ada."}]', 7),
('3035b91b-07f4-475d-93f4-e6b94398085a', 's8', 'Fintech Lending', 'Anda sudah punya satu cicilan pinjol. Datang tawaran pinjol lain untuk ''menutup'' cicilan pertama dengan tenor lebih panjang. Keputusan Anda?', '[{"t":"Ambil, supaya cicilan bulanan lebih ringan","quality":0,"outcome":"Anda masuk pola ''gali lubang tutup lubang''."},{"t":"Hentikan menambah utang, susun rencana pelunasan yang realistis","quality":2,"outcome":"Anda memutus rantai utang."},{"t":"Ambil tapi berjanji ini yang terakhir","quality":1,"outcome":"Niat baik tanpa rencana konkret jarang berhasil."}]', 8);

-- 5. SEED SIM EVENTS
INSERT INTO `sim_events` (`id`, `slug`, `theme`, `icon`, `text`, `choices`, `order_num`) VALUES
('f7bbca40-bf5e-47fc-83b2-b7aec99aad48', 'e1', 'Anggaran Awal', '📊', 'Uang bulanan Rp3.000.000 baru masuk. Apa langkah pertama Anda?', '[{"t":"Sisihkan Rp600.000 untuk tabungan dulu, baru atur sisanya","quality":2,"dBalance":0,"dSaving":600000,"outcome":"Bijak — ''membayar diri sendiri dulu'' mengamankan tabungan."},{"t":"Belanja dulu sesuai keinginan, sisanya baru ditabung","quality":0,"dBalance":0,"dSaving":0,"outcome":"Berisiko — menabung dari ''sisa'' sering berakhir tanpa tabungan."},{"t":"Tabung setengahnya, Rp1.500.000","quality":1,"dBalance":0,"dSaving":1500000,"outcome":"Niat baik, tetapi terlalu ketat bisa membuat kehabisan."}]', 1),
('e300cd0b-fbd6-4eed-9df2-87e68b41c57b', 'e2', 'Pinjaman Online', '💸', 'Muncul iklan: ''Pinjaman cair 5 menit tanpa syarat, cukup izinkan akses kontak''. Anda sedang ingin membeli gawai baru.', '[{"t":"Abaikan — ini ciri pinjol ilegal dan saya tidak butuh utang untuk keinginan","quality":2,"dBalance":0,"dSaving":0,"outcome":"Tepat. Anda menghindari jebakan utang berbunga tinggi."},{"t":"Ambil pinjaman untuk beli gawai sekarang","quality":0,"dBalance":-500000,"dSaving":0,"outcome":"Bunga dan biaya tersembunyi menggerus saldo Anda."},{"t":"Ambil pinjaman kecil saja untuk coba-coba","quality":0,"dBalance":-200000,"dSaving":0,"outcome":"Meski kecil, Anda kini terikat pinjol berisiko."}]', 2),
('49a8408b-c4cd-42d6-8e81-f45102d6a6ce', 'e3', 'Penipuan Pembayaran', '🎣', 'SMS: ''Selamat! Anda menang undian Rp10.000.000. Bayar pajak Rp300.000 dulu ke rekening ini untuk mencairkan.''', '[{"t":"Abaikan — undian sah tidak meminta bayar di muka","quality":2,"dBalance":0,"dSaving":0,"outcome":"Benar. ''Bayar dulu untuk dapat hadiah'' adalah ciri penipuan."},{"t":"Bayar Rp300.000, hadiahnya jauh lebih besar","quality":0,"dBalance":-300000,"dSaving":0,"outcome":"Uang Anda hilang dan hadiah tidak pernah ada."},{"t":"Balas untuk menanyakan detail undian","quality":1,"dBalance":0,"dSaving":0,"outcome":"Membalas menandakan nomor Anda aktif."}]', 3),
('bc48fc7c-78e9-4aba-a8f0-cef906b5e9c9', 'e4', 'Keamanan Akun', '🔐', 'Sebuah aplikasi keuangan baru meminta Anda membuat kata sandi dan menawarkan login lebih cepat tanpa verifikasi tambahan.', '[{"t":"Pakai kata sandi unik & aktifkan autentikasi dua faktor (2FA)","quality":2,"dBalance":0,"dSaving":0,"outcome":"Aman. 2FA membuat akun tetap terlindungi."},{"t":"Pakai kata sandi yang sama dengan akun lain agar mudah diingat","quality":0,"dBalance":0,"dSaving":0,"outcome":"Berisiko — bila satu akun bobol, semua terancam."},{"t":"Lewati 2FA supaya login lebih cepat","quality":1,"dBalance":0,"dSaving":0,"outcome":"Kurang aman."}]', 4),
('c5d7b2ec-567e-47b6-9d64-7f98d5e05a48', 'e5', 'Investasi', '📈', 'Anda punya tabungan Rp600.000 lebih. Seorang teman menawarkan ''investasi untung 20% per bulan dijamin tanpa risiko''.', '[{"t":"Tolak; pelajari produk investasi resmi yang sesuai profil risiko","quality":2,"dBalance":0,"dSaving":0,"outcome":"Tepat. ''Untung tinggi dijamin tanpa risiko'' tidak ada."},{"t":"Masukkan semua tabungan, mumpung untung besar","quality":0,"dBalance":0,"dSaving":-600000,"outcome":"Skema runtuh dan tabungan Anda hilang."},{"t":"Coba dengan setengah tabungan saja","quality":0,"dBalance":0,"dSaving":-300000,"outcome":"Tetap rugi."}]', 5),
('451c5b25-a968-4f43-a770-dd8f6b4d12b8', 'e6', 'Perlindungan Konsumen', '⚖️', 'Di akhir bulan Anda menyadari ada potongan biaya Rp50.000 yang tak pernah dijelaskan oleh sebuah layanan.', '[{"t":"Kumpulkan bukti, ajukan keluhan resmi ke penyedia; bila buntu, ke OJK","quality":2,"dBalance":50000,"dSaving":0,"outcome":"Tepat. Anda menggunakan hak konsumen."},{"t":"Biarkan saja, jumlahnya kecil","quality":1,"dBalance":0,"dSaving":0,"outcome":"Hak Anda terlepas."},{"t":"Tutup akun dan pindah tanpa mengadu","quality":1,"dBalance":0,"dSaving":0,"outcome":"Anda menghindar, tetapi tidak menyelesaikan masalah."}]', 6);
